fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # ruff version.
    rev: v0.6.2
    hooks:
        # run formatter
      - id: ruff-format
        types_or: [ python, pyi ]
        # Run the linter.
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix, --exit-non-zero-on-fix ]
        require_serial: true
